### ISSUE TITLE
New Customer Signup

### ISSUE THREAD

**Issue by kovidiament** [nyu-devops-fall22/customers#1]
**As a** user
 **I need** the ability to sign up as a new customer, and be assigned a unique customer ID, by providing my first name and last name, and address  
 **So that** I have an account to use the service 
   
 ### Details and Assumptions
Customers must have a first and last name, and at least one address
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a first name, last name, address
 When I request to create a new customer account with this information
 Then if a customer with this exact information does not already exist, a new customer account is created and a unique ID for the customer is returned.
 ```

**Comment by kovidiament** [comment]
customers have a first and last name and "at least one" address.

**Comment by kovidiament** [comment]
ability to add additional addresses may be added as a separate feature later

**Comment by omb244** [comment]
Do you think we can link sign up with other user accounts like Google, Apple, Facebook etc..?

**Comment by kovidiament** [comment]
I think that may be much more complicated than the professor has in mind. He mentioned in lecture that the code-writing is not supposed to be hard at all, the point is just working as team. Something along the lines of "Writing code is what we do in order to work as a team." 
If you look at HW1 grading criteria:
![image](https://user-images.githubusercontent.com/31549975/193292224-45ae36e8-f0f9-4ba3-a34d-62889a4d1feb.png)
![image](https://user-images.githubusercontent.com/31549975/193292291-94ade6bf-a201-44cd-ba07-64760fb0060a.png)
![image](https://user-images.githubusercontent.com/31549975/193292344-fbd390f6-a7f7-4c01-b98a-0b377d0fc281.png)

**Comment by SamSloboda** [comment]
We need to also make sure that the user with similar username or email.

**Comment by Tazhio** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/customers-6333a59457678a0019763df8/issues/nyu-devops-fall22/customers/1?planning-poker) with Zenhub @kovidiament @omb244 @SamSloboda
