### ISSUE TITLE
Creating Databases

### ISSUE THREAD

**Issue by SamSloboda** [nyu-devops-fall22/customers#10]
**As a** service provider
 **I need** an SQL databases to store user's ID, first name, last name, address 1 and address 2 (optional), isActive.
 **So that** I can retrieve them anytime using REST APIs.
   
 ### Details and Assumptions
 * We will be using SQL Database.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given query is called
 When database receives the request query and is executed
 Then database is successfully created
 ```

**Comment by Tazhio** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/customers-6333a59457678a0019763df8/issues/nyu-devops-fall22/customers/10?planning-poker) with Zenhub @kovidiament @omb244 @SamSloboda

**Comment by SamSloboda** [comment]
I have moved this issue to the "Done" section as it was covered with #17.
