### ISSUE TITLE
Update Customer Details 

### ISSUE THREAD

**Issue by omb244** [nyu-devops-fall22/customers#3]
**As a** customer
 **I need** the ability to be able to change my profile information (first name, last name, address)
 **So that** I am able to update my personal information.
   
 ### Details and Assumptions
 * Every customer has first name, last name, and address.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given unique user ID
 When user intents to update first name, last name, or address
 Then the personal information will be changed in database
 ```

**Comment by Tazhio** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/customers-6333a59457678a0019763df8/issues/nyu-devops-fall22/customers/3?planning-poker) with Zenhub @SamSloboda @omb244 @kovidiament
