### ISSUE TITLE
Listing Customers

### ISSUE THREAD

**Issue by SamSloboda** [nyu-devops-fall22/customers#7]
**As a** service provider 
 **I need** to be able to list all of the customers 
 **So that** I will be able to see if all of the customers are correctly listed from the database
   
 ### Details and Assumptions
 * We have multiple users in the database and we need to list them
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given we have users listed in the database
 When list users is requested
 Then JSON of all users should be returned
 ```

**Comment by Tazhio** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/customers-6333a59457678a0019763df8/issues/nyu-devops-fall22/customers/7?planning-poker) with Zenhub @SamSloboda @omb244 @kovidiament
